spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gratulo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 1000
      connection-timeout: 1000
      maximum-pool-size: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

scheduling:
  enabled: true

telegram:
  bot:
    name: GratuloBot
    token: 5693326064:AAEnVN2gbJ7VTTiNYCKbywa3XL1HYiJOmXw
  chat:
    id: -757393370